---

- name: check if icinga2 ido table and user in mysql exist
  shell: >
    mysql
    --user={{ icinga2_master_icinga2_database_user }} 
    --password={{ icinga2_master_icinga2_database_pass }}
    --host={{ icinga2_master_icinga2_database_host }}
    --ssl-ca={{ icinga2_master_ca_path }}
    {{ icinga2_master_icinga2_database_name }}
    -e "SHOW TABLES;" | grep "icinga_hosts"
  register: icinga2_master_register_icinga2_imported
  changed_when: icinga2_master_register_icinga2_imported.rc == 1
  failed_when: "'Access denied for' in icinga2_master_register_icinga2_imported.stderr"
  when: icinga2_master_ido_enabled

- name: import icinga2 ido database schema using the root user
  mysql_db:
    name: '{{ icinga2_master_icinga2_database_name }}'
    login_host: '{{ icinga2_master_icinga2_database_host }}'
    login_port: '{{ icinga2_master_icinga2_database_port }}'
    login_user: '{{ icinga2_master_db_root_user }}'
    login_password: '{{ icinga2_master_db_root_pass }}'
    ssl_ca: '{{ icinga2_master_ca_path }}'
    state: import
    target: /usr/share/icinga2-ido-mysql/schema/mysql.sql
  run_once: True
  when: icinga2_master_register_icinga2_imported.rc == 1 and icinga2_master_ido_enabled

- name: create a user with access only to the ido database using the root user
  mysql_user:
    name: '{{ icinga2_master_icinga2_database_user }}'
    password: '{{ icinga2_master_icinga2_database_pass }}'
    priv: '{{ icinga2_master_icinga2_database_name }}.*:ALL'
    login_host: '{{ icinga2_master_icinga2_database_host }}'
    login_port: '{{ icinga2_master_icinga2_database_port }}'
    login_user: '{{ icinga2_master_db_root_user }}'
    login_password: '{{ icinga2_master_db_root_pass }}'
    ssl_ca: '{{ icinga2_master_ca_path }}'
    state: present
  run_once: True
  when: icinga2_master_register_icinga2_imported.rc == 1 and icinga2_master_ido_enabled

- name: configure icinga2 ido feature
  template:
    src: templates/etc/icinga2/features-available/ido-mysql.conf.j2
    dest: /etc/icinga2/features-available/ido-mysql.conf
    owner: icinga
    group: icinga
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  when: icinga2_master_ido_enabled

- name: enable icinga2 ido feature
  file:
    src: /etc/icinga2/features-available/ido-mysql.conf
    dest: /etc/icinga2/features-enabled/ido-mysql.conf
    state: link
  when: icinga2_master_ido_enabled

- name: install icinga2 constants configuration
  template:
    src: templates/etc/icinga2/constants.conf.j2
    dest: /etc/icinga2/constants.conf
    owner: icinga
    group: icinga
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  notify: icinga2_master reload icinga2

- name: remove files from conf.d which are already defined in global-templates
  file:
    name: '{{ item }}'
    state: absent
  with_items:
    - /etc/icinga2/conf.d/commands.conf
    - /etc/icinga2/conf.d/services.conf
    - /etc/icinga2/conf.d/templates.conf

- name: add our own host configuration
  template:
    src: templates/etc/icinga2/zones.d/generic_host.conf.j2
    dest: '/etc/icinga2/zones.d/{{ hostvars[item].icinga2_master_client_parent_zone }}/{{ hostvars[item].inventory_hostname }}_host.conf'
    owner: icinga
    group: icinga
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  loop: '{{ groups["monitoring-master"] }}'
  notify: icinga2_master reload icinga2
  when: inventory_hostname == icinga2_client_monitoring_parents[0]

- name: install icinga2 api-users configuration
  template:
    src: templates/etc/icinga2/conf.d/api-users.conf.j2
    dest: /etc/icinga2/conf.d/api-users.conf
    owner: icinga
    group: icinga
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  notify: icinga2_master reload icinga2

- name: execute icinga2 api setup command
  command: icinga2 api setup
  args:
    creates: /var/lib/icinga2/ca/ca.crt
  notify: icinga2_master reload icinga2

- name: configure icinga2 api feature
  template:
    src: templates/etc/icinga2/features-available/api.conf.j2
    dest: /etc/icinga2/features-available/api.conf
    owner: icinga
    group: icinga
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0

- name: enable icinga2 api feature
  file:
    src: /etc/icinga2/features-available/api.conf
    dest: /etc/icinga2/features-enabled/api.conf
    state: link

- name: configure icinga2 graphite feature
  template:
    src: templates/etc/icinga2/features-available/graphite.conf.j2
    dest: /etc/icinga2/features-available/graphite.conf
    owner: icinga
    group: icinga
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  when: icinga2_master_graphite_enabled
  notify: icinga2_master reload icinga2

- name: enable icinga2 graphite feature
  file:
    src: /etc/icinga2/features-available/graphite.conf
    dest: /etc/icinga2/features-enabled/graphite.conf
    state: link
  when: icinga2_master_graphite_enabled
  notify: icinga2_master reload icinga2

# Global Icinga2 configuration
- name: ensure the global-templates directory is present
  file:
    dest: /etc/icinga2/zones.d/global-templates
    owner: icinga
    group: icinga
    mode: 0755
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
    state: directory
  when: inventory_hostname == icinga2_client_monitoring_parents[0]

- name: create global template configurations
  template:
    src: templates/etc/icinga2/zones.d/global-templates/{{ item }}.j2
    dest: /etc/icinga2/zones.d/global-templates/{{ item }}
    owner: icinga
    group: icinga
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  with_items:
    - services.conf
    - templates.conf
    - commands.conf
  when: inventory_hostname == icinga2_client_monitoring_parents[0]

- name: create global zones configuration
  template:
    src: templates/etc/icinga2/zones.conf.j2
    dest: /etc/icinga2/zones.conf
    owner: icinga
    group: icinga
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  notify: icinga2_master reload icinga2

- name: create zone configuration directory for each host
  file:
    path: '/etc/icinga2/zones.d/{{ hostvars[item].icinga2_master_client_parent_zone }}'
    state: directory
    owner: icinga
    group: icinga
    mode: 0755
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  loop: '{{ groups["monitoring-client"] }}'
  notify: icinga2_master reload icinga2
  when: inventory_hostname == icinga2_client_monitoring_parents[0]

- name: create zone file for each zone
  template:
    src: templates/etc/icinga2/zones.d/generic_zone.conf.j2
    dest: '/etc/icinga2/zones.d/{{ hostvars[item].icinga2_master_client_parent_zone }}/{{ hostvars[item].inventory_hostname }}_zone.conf'
    owner: icinga
    group: icinga
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  loop: '{{ groups["monitoring-client"] }}'
  notify: icinga2_master reload icinga2
  when: inventory_hostname == icinga2_client_monitoring_parents[0]

- name: create host file per host
  template:
    src: templates/etc/icinga2/zones.d/generic_host.conf.j2
    dest: '/etc/icinga2/zones.d/{{ hostvars[item].icinga2_master_client_parent_zone }}/{{ hostvars[item].inventory_hostname }}_host.conf'
    owner: icinga
    group: icinga
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: icinga2_etc_t
    selevel: s0
  loop: '{{ groups["monitoring-client"] }}'
  notify: icinga2_master reload icinga2
  when: inventory_hostname == icinga2_client_monitoring_parents[0]

- name: ensure that icinga2 is started and enabled on boot
  service:
    name: icinga2
    state: started
    enabled: yes
