---

- name: include os specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - 'role::icinga2_master'
    - 'role::icinga2_master:config'

- import_tasks: configuration.yml
  tags:
    - 'role::icinga2_master'
    - 'role::icinga2_master:config'
