name: CI - Linting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: icinga2_master

    # Checkout Adfinis lint-rules
    - uses: actions/checkout@v2
      with:
        repository:  adfinis-sygroup/ansible-lint-rules
        path: lint-rules

    - name: ansible-lint
      uses: ansible/ansible-lint-action@master
      with:
        targets: "icinga2_master"
        args: "-R -r lint-rules"

    - name: yamllint
      uses: karancode/yamllint-github-action@v1.0.0
      with:
        yamllint_config_filepath: icinga2_master/.testenv/yamllint.yml
